const herramientas = [
    {
        id: 1,  
        categoria: "Herramientas Eléctricas",
        nombre: "Taladro Percutor Profesional",
        descripcion: "1200w con mandril 13mm",
        precio: 55990,
        precioFormateado: "$55990",
        imagen: "../imagenes/Productos/taladropercutor.png",
        alt: "Taladro Percutor Profesional",
        destacado: true,
    },
    {
        id: 2,  
        categoria: "Herramientas Manuales",
        nombre: "Set de Llaves Combinadas",
        descripcion: "12 piezas, 8-19mm, acero cromo vanadio.",
        precio: 18990,
        precioFormateado: "$18990",
        imagen: "../imagenes/productos/setdellaves.jpg",
        alt: "Set de Llaves Combinadas",
        destacado: true,
    },
    {
        id: 3,  
        categoria: "Seguridad Industrial",
        nombre: "kit de Seguridad",
        descripcion: "Cascos, guantes y lentes de seguridad.",
        precio: 15990,
        precioFormateado: "$15990",
        imagen: "../imagenes/productos/kitdeseguridad.jpg   ", 
        alt: "kit de Seguridad",
        destacado: true,
    },
    {
        id: 4,
        categoria: "Material Eléctrico",
        nombre: "Cable Eléctrico 2x2.5mm",
        descripcion: "Rollo de 100 metros, calidad industrial.",
        precio: 8990,
        precioFormateado: "$8990",
        imagen: "../imagenes/productos/rollocable2x2.5mm.jpg",
        alt: "Cable Eléctrico 2x2.5mm",
        destacado: true,
    },
    {
        id: 5,
        categoria: "Materiales de Construcción",
        nombre: "Cemento Weber Super Pinguino x 25kg",
        descripcion: "Mortero a base de cemento blanco.",
        precio: 58990,
        precioFormateado: "$58990",
        imagen: "../imagenes/productos/cemento.png",
        alt: "Cemento Weber Super Pinguino x 25kg",
        destacado: true,
    },
    {
        id: 6,
        categoria: "Pinturas",
        nombre: "Pintura de Poliuretano Industrial",
        descripcion: "Pintura de Poliuretano Industrial Blanca mate. 20 litros.",
        precio: 318990,
        precioFormateado: "$318990",
        imagen: "../imagenes/productos/pintura.png",
        alt: "Pintura de Poliuretano Industrial",
        destacado: true,
    }
];  
